const ADD_NEW_USER_REQUEST = 'ADD_NEW_USER_REQUEST';
const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE';

export {
  ADD_NEW_USER_REQUEST,
  ADD_NEW_USER_SUCCESS,
  ADD_NEW_USER_FAILURE,
};
