const ADD_NEW_USER_REQUEST = 'ADD_NEW_USER_REQUEST';
const ADD_NEW_USER_SUCCESS = 'ADD_NEW_USER_SUCCESS';
const ADD_NEW_USER_FAILURE = 'ADD_NEW_USER_FAILURE';

const FETCH_FULL_DATA_REQUEST = 'FETCH_FULL_DATA_REQUEST';
const FETCH_FULL_DATA_SUCCESS = 'FETCH_FULL_DATA_SUCCESS';
const FETCH_FULL_DATA_FAILURE = 'FETCH_FULL_DATA_FAILURE';

export {
  FETCH_FULL_DATA_REQUEST,
  FETCH_FULL_DATA_SUCCESS,
  FETCH_FULL_DATA_FAILURE,
  ADD_NEW_USER_REQUEST,
  ADD_NEW_USER_SUCCESS,
  ADD_NEW_USER_FAILURE,
};
