const FETCH_USER_EXIST_REQUEST = 'FETCH_USER_EXIST_REQUEST';
const FETCH_USER_EXIST_SUCCESS = 'FETCH_USER_EXIST_SUCCESS';
const FETCH_USER_EXIST_FAILURE = 'FETCH_USER_EXIST_FAILURE';

const FETCH_USER_DATA_REQUEST = 'FETCH_USER_DATA_REQUEST';
const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
const FETCH_USER_DATA_FAILURE = 'FETCH_USER_DATA_FAILURE';

const RESET_SEARCH_STEPS = 'RESET_SEARCH_STEPS';
const FETCH_ERROR_STEP = 'FETCH_ERROR_STEP';


export {
  RESET_SEARCH_STEPS,
  FETCH_ERROR_STEP,
  FETCH_USER_DATA_REQUEST,
  FETCH_USER_DATA_SUCCESS,
  FETCH_USER_DATA_FAILURE,
  FETCH_USER_EXIST_REQUEST,
  FETCH_USER_EXIST_SUCCESS,
  FETCH_USER_EXIST_FAILURE,
};
