language: node_js

cache:
  bundler: true
  directories:
    - node_modules

bundler_args: --without production

before_install:
  - "npm install -g yarn"

install:
  - yarn
script:
  - "bundle exec rspec spec/"
  - "bundle exec rubocop"
  - "yarn lint"
  - "yarn test"
