const OPEN_ADD_MODAL = 'OPEN_ADD_MODAL';
const CLOSE_ADD_MODAL = 'CLOSE_ADD_MODAL';

const OPEN_FUSE_MODAL = 'OPEN_FUSE_MODAL';
const CLOSE_FUSE_MODAL = 'CLOSE_FUSE_MODAL';

const OPEN_SIDEMENU = 'OPEN_SIDEMENU';
const CLOSE_SIDEMENU = 'CLOSE_SIDEMENU';

export {
  OPEN_ADD_MODAL,
  OPEN_FUSE_MODAL,
  OPEN_SIDEMENU,
  CLOSE_ADD_MODAL,
  CLOSE_FUSE_MODAL,
  CLOSE_SIDEMENU,
};
