const HERO_ICONS = {
  ana:        'https://blzgdapipro-a.akamaihd.net/hero/ana/hero-select-portrait.png',
  bastion:    'https://blzgdapipro-a.akamaihd.net/hero/bastion/hero-select-portrait.png',
  doomfist:   'https://blzgdapipro-a.akamaihd.net/hero/doomfist/hero-select-portrait.png',
  dVa:        'https://blzgdapipro-a.akamaihd.net/hero/dva/hero-select-portrait.png',
  genji:      'https://blzgdapipro-a.akamaihd.net/hero/genji/hero-select-portrait.png',
  hanzo:      'https://blzgdapipro-a.akamaihd.net/hero/hanzo/hero-select-portrait.png',
  junkrat:    'https://blzgdapipro-a.akamaihd.net/hero/junkrat/hero-select-portrait.png',
  lucio:      'https://blzgdapipro-a.akamaihd.net/hero/lucio/hero-select-portrait.png',
  mccree:     'https://blzgdapipro-a.akamaihd.net/hero/mccree/hero-select-portrait.png',
  mei:        'https://blzgdapipro-a.akamaihd.net/hero/mei/hero-select-portrait.png',
  moira:      'https://blzgdapipro-a.akamaihd.net/hero/moira/hero-select-portrait.png',
  mercy:      'https://blzgdapipro-a.akamaihd.net/hero/mercy/hero-select-portrait.png',
  orisa:      'https://blzgdapipro-a.akamaihd.net/hero/orisa/hero-select-portrait.png',
  pharah:     'https://blzgdapipro-a.akamaihd.net/hero/pharah/hero-select-portrait.png',
  reaper:     'https://blzgdapipro-a.akamaihd.net/hero/reaper/hero-select-portrait.png',
  reinhardt:  'https://blzgdapipro-a.akamaihd.net/hero/reinhardt/hero-select-portrait.png',
  roadhog:    'https://blzgdapipro-a.akamaihd.net/hero/roadhog/hero-select-portrait.png',
  soldier76:  'https://blzgdapipro-a.akamaihd.net/hero/soldier-76/hero-select-portrait.png',
  sombra:     'https://blzgdapipro-a.akamaihd.net/hero/sombra/hero-select-portrait.png',
  symmetra:   'https://blzgdapipro-a.akamaihd.net/hero/symmetra/hero-select-portrait.png',
  torbjorn:   'https://blzgdapipro-a.akamaihd.net/hero/torbjorn/hero-select-portrait.png',
  tracer:     'https://blzgdapipro-a.akamaihd.net/hero/tracer/hero-select-portrait.png',
  widowmaker: 'https://blzgdapipro-a.akamaihd.net/hero/widowmaker/hero-select-portrait.png',
  winston:    'https://blzgdapipro-a.akamaihd.net/hero/winston/hero-select-portrait.png',
  zarya:      'https://blzgdapipro-a.akamaihd.net/hero/zarya/hero-select-portrait.png',
  zenyatta:   'https://blzgdapipro-a.akamaihd.net/hero/zenyatta/hero-select-portrait.png',
};

export default HERO_ICONS;
